name: CI/CD Pipeline - EC2 Deploy (Optimized with Custom Image)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: '22'
  PNPM_VERSION: '10.18'
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  # Job de testes e build usando imagem customizada
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    # Usar imagem Docker customizada com dependências pré-instaladas
    container:
      image: ghcr.io/tickets-publicos/tickets-transporte-publico-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Dependências já estão na imagem, apenas sincronizar se necessário
      - name: Sync dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      # Prisma Client já foi gerado na imagem, mas regenerar se schema mudou
      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: apps/api

      - name: Run linting
        run: pnpm lint

      - name: Run type checking
        run: pnpm check-types

      - name: Run tests (API)
        run: pnpm --filter nest test:full

      # Nota: Testes E2E requerem PostgreSQL configurado
      # Execute localmente com: pnpm --filter nest test:e2e
      # Certifique-se de ter um banco de dados PostgreSQL rodando

      - name: Build applications
        run: pnpm build

  # Job de deploy para EC2
  deploy-to-ec2:
    name: Deploy to EC2
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            # Navegar para o diretório do projeto
            cd /home/${{ secrets.EC2_USERNAME }}/tickets-transporte-publico
            
            # Fazer backup do .env
            cp .env .env.backup
            
            # Atualizar código
            git fetch origin
            git reset --hard origin/main
            
            # Restaurar .env
            cp .env.backup .env
            
            # Parar containers
            docker-compose -f docker-compose.prod.yml down
            
            # Rebuild e reiniciar containers
            docker-compose -f docker-compose.prod.yml up -d --build
            
            # Executar migrations
            docker exec tickets-api npx prisma migrate deploy
            
            # Limpar recursos não utilizados
            docker system prune -f
            
            # Verificar status
            docker-compose -f docker-compose.prod.yml ps
            
            echo "✅ Deploy concluído com sucesso!"

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            # Esperar containers iniciarem
            sleep 10
            
            # Verificar health da API
            curl -f http://localhost:3000/health || exit 1
            
            # Verificar health do Web
            curl -f http://localhost:3001 || exit 1
            
            echo "✅ Verificação de saúde concluída!"

      - name: Notify deployment status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ job.status }}' === 'success' ? '✅ Sucesso' : '❌ Falhou';
            const color = '${{ job.status }}' === 'success' ? '28a745' : 'dc3545';
            
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: '${{ job.status }}',
              description: `Deploy para EC2 ${status}`,
              context: 'Deploy EC2'
            });